version: '3.8'

services:
  adminer:
    container_name: adminer
    hostname: adminer
    build:
      context: .
      dockerfile: ./services/adminer/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - main

  db:
    container_name: db
    hostname: db
    build:
      context: .
      dockerfile: ./services/db/Dockerfile
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localhost -d piscineds"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - main

  python-runner:
    container_name: python-runner
    hostname: python-runner
    build:
      context: .
      dockerfile: ./services/python-runner/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    tty: true
    networks:
      - main

networks:
  main:
    name: main
    driver: bridge